POST http://localhost:5000/api/createMeme?api_key=wdb7qcoj0bryfe8vkwufvk
Content-Type: application/json

 {
     "top_text": "dfsdsfd",
     "bottom_text": "dfsddgf",
     "file": "evil-kid"
 }

###
GET http://localhost:5000/api/getDefaultMemes?api_key=wdb7qcoj0bryfe8vkwufvk

###
GET http://localhost:5000/api/getGeneratedMemes

###
GET http://localhost:5000/api/getGeneratedMemes?offset=1&limit=3?api_key=wdb7qcoj0bryfe8vkwufvk

###
DELETE http://localhost:5000/api/deleteGeneratedMemes?api_key=wdb7qcoj0bryfe8vkwufvk