POST http://localhost:5000/api/meme-builder/generateMemes
Content-Type: application/json

 {
     "top_text": "Ordinar",
     "bottom_text": "Extraordinar",
     "file": "willy-wonka"
 }

###
GET http://localhost:5000/api/meme-builder/getDefaultMemes

###
GET http://localhost:5000/api/meme-builder/getGeneratedMemes